name: Daily Celebration Scraper

on:
  schedule:
    # - cron: '*/5 * * * *'  # every 5 minutes
    - cron: '1 0 * * *' # every 00.01

  workflow_dispatch:

jobs:
  scrape:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v3
      with:
        token: ${{ secrets.PAT_TOKEN }}
        fetch-depth: 0
        ref: main

    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.x'

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt

    - name: Run scraper script
      run: python celebration-scraper.py

    - name: Commit and push CSV changes
      env:
        PAT_TOKEN: ${{ secrets.PAT_TOKEN }}
      run: |
        git config --global user.name "github-actions"
        git config --global user.email "github-actions@github.com"

        # Override the remote to use the PAT token
        git remote set-url origin https://x-access-token:${PAT_TOKEN}@github.com/${{ github.repository }}

        git add celebration-scraper.csv

        if git diff --cached --quiet; then
          echo "No changes to commit."
        else
          git commit -m "Update celebration CSV"
          git push origin main
        fi
